### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by nc1z** [nc1z/Asset-Screener-App#25]
- **Server Deployment via Cyclic**
  - To `npm init -y` in root folder
    - Add workspaces to package.json + start script to cd into server and npm start
  - Go into server scripts and add a start script, change current start script to start:dev or dev
  
- **Client Deployment via Netlify**
  - To create _redirects file in public folder (to prevent routing problems after deployment)
  - To `npm run build` and generate build folder

**Comment by desmondtansl** [comment]
Backend deployment completed

**Comment by nc1z** [comment]
Frontend deployment completed
