### ISSUE TITLE
[Server] Additional Security Checks - Ticket Submission

### ISSUE THREAD

**Issue by nc1z** [nc1z/Asset-Screener-App#41]
- Ensure negative req.body.amount numbers doesn't go through
- Ensure non Number type in req.body.amount doesn't go through

**Additional security (optional):**
- Ensure non BTC, ETH, USDT doesn't go through
- Ensure non Allocate/Remove doesn't go through

**Comment by desmondtansl** [comment]
Form validation done and tested in test environment and working as intended in production
